apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: candle-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/version: "16.13"
spec:
  selector:
    app.kubernetes.io/name: candle-postgres
    app.kubernetes.io/component: database
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
